# Site settings
title: Xtend - Modernized Java
email: sven.efftinge@typefox.io
description: > # this means to ignore newlines until "baseurl:"
  Xtend is a flexible and expressive dialect of Java, which compiles into readable
  Java 5 compatible source code. You can use any existing Java library seamlessly.
  The compiled output is readable and pretty-printed, and tends to run as fast as
  the equivalent handwritten Java code.
baseurl: "/xtend" # the subpath of your site, e.g. /blog/
url: "http://xtend-lang.org" # the base hostname & protocol for your site
twitter_username: xtendlang
github_username:  xtext
encoding: UTF-8
exclude:
  - README.md
  - Gemfile

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  #auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..4
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

src:
  xtext: "https://github.com/eclipse/xtext/blob/v2.7.0"

javadoc:
  xtext: "http://download.eclipse.org/modeling/tmf/xtext/javadoc/2.8"
  java: "http://docs.oracle.com/javase/8/docs/api"
  guava: "http://docs.guava-libraries.googlecode.com/git-history/release/javadoc"

edit-repo : "https://github.com/eclipse/xtext/edit/maintenance/xtend-website/"
